name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 12.16.1
      
      - name: Install dependencies
        run: npm install

      - name: Publish to npm
        run: npm run np
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
